### PR TITLE
Adding Unit Test

### LINKED ISSUE #20: Add Unit Tests
#### Description:

As in header

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

 Closes #20 

 

 ### Test files

All scripts used for creating the unit tests are in [this folder](https://burohappold.sharepoint.com/:f:/s/BHoM/EvtPsjoHWl5MssJmLbeSz5QBHkXVcERfYsKxpJkeyXKnAA?e=kVrd3j).

 ### Changelog

- Adding the unit tests to the `Clipper_Toolkit` for following methods:
  - Compute: `Offset()`.

### CODE REVIEW

**Comment by LMarkowski** [comment]
@BHoMBot check tests

**Comment by LMarkowski** [comment]
@BHoMBot check unit tests

**Review by rolyhudson — APPROVED** [review]
Reviewed the creation of unit tests and run check test locally with no problems.

**Pull request merged**
